module.exports = {
    devServer:{
        proxy:{
            '/ajax':{
                target:'https://m.maoyan.com',
                changeOrigin:true
            },
            '/geoip/':{
                target:'https://api.asilu.com',
                changeOrigin:true
            },
            '/v2/movie/':{
                target:'https://api.douban.com',
                changeOrigin:true
            },
            '/j/search_subjects':{
                target:'https://movie.douban.com',
                changeOrigin:true
            }
        }
    }
}